using Painting;

namespace DefaultNamespace.TextureGeneration
{
    public static class TextureInputs
    {
        public static readonly WaveFunctionCollapse.Tile Metal = new(new string[] {
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW-----WWWWWWW-----",
            "----WWWWWWWWWWW------WWWWW------",
            "------WWWWWWW--------WWWWW------",
            "-DDD--WWWWWWW--------WWWWW------",
            "-DDD--WWWWWWW--------WWWWW------",
            "-DDD--WWWWWWW--------WWWWW------",
            "-DDD--WWWWWWW--DDD----WWW-------",
            "------WWWWWWW--DDD----WWW-------",
            "------WWWWWWW--DDD----WWW-------",
            "------WWWWWWW---------WWW-------",
            "------WWWWWWW---------WWW-------",
            "--------WWWW-----DDD------------",
            "--------WWWW-----DDD------------",
            "-DDD----WWWW--------------------",
            "-DDD----WWWW--------------------",
            "-DDD----WWWW-------DDDDDDDDDDDDD",
            "--------WWWW-------DDDDDDDDDDDDD",
            "-------------------DDDDDDDDDDDDD",
            "-------------------DDDDDDDDDDDDD",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "D----DDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "D----DDDDDDDDDDDDDD-----DDDDDDDD",
            "D----DDDDDDDDDDDDDD-----DDDDDDDD",
            "D----DDDDDDDDDDDDDDDDDDDDDDDDDDD",
        });

        // A: color = new UnityEngine.Color(0.65f, 0.803f, 0.847f, 1f);
        // B: color = new UnityEngine.Color(0.843f, 0.843f, 0.866f, 1f);
        // C: color = new UnityEngine.Color(0.098f, 0.137f, 0.262f, 1f);
        public static readonly WaveFunctionCollapse.Tile Sofa = new(new string[] {
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            "AAABBBCCCCCCCAAABBBCCCCCCCAAABBB",
            });

        // -: color = new UnityEngine.Color(0.572f, 0.572f, 0.572f, 1f);
        // B: color = new UnityEngine.Color(0.341f, 0.341f, 0.341f, 1f);
        // C: color = new UnityEngine.Color(0.494f, 0.494f, 0.494f, 1f);
        public static readonly WaveFunctionCollapse.Tile Wall = new(new string[] {
            "-------------------CCCC---------",
            "---B--------BBBB---CCCC---------",
            "--------------------------------",
            "--------B-----------------------",
            "--------------------------------",
            "-----CCCCCCC------BBBBBBB-------",
            "-----CCCCCCC------BBBBBBB-------",
            "--------------------------------",
            "------BBB-----------------------",
            "------BBB---------CCCC----------",
            "------BBB---------CCCC----------",
            "------------------CCCC----------",
            "------------------CCCC----------",
            "--------------------------------",
            "--------------------------------",
            "-------------------------BBBBB--",
            "--CCCCCCCCCCCC------------------",
            "--------------------------------",
            "----------------------CC--------",
            "---------BBBB---------CC--------",
            "---------BBBB---------CC--------",
            "--------------------------------",
            "--CCCCC-------------------------",
            "--CCCCC---------------BBBB------",
            "--CCCCC---------------BBBB------",
            "----------------------BBBB------",
            "--------------------------------",
            "-----BBBBBB---------------------",
            "----------------------CCC-------",
            "--------------------------------",
            "----CCCCCCCCCCCC----------------",
            "----CCCCCCCCCCCC----------------",
            });

        // -: color = new UnityEngine.Color(0.99f, 0.784f, 0.211f, 1f);
        // W: color = new UnityEngine.Color(0.98f, 0.874f, 0.419f, 1f);
        public static readonly WaveFunctionCollapse.Tile Window = new(new string[] {
            "--------------------------------",
            "----WWW-------------------------",
            "--WW--WW------------------------",
            "-WW----WW-----------------------",
            "-WW-----WW----------------------",
            "-W-------WW---------------------",
            "-WW-------WW--------------------",
            "--WW-----WW---------------------",
            "---WW---WW----------------------",
            "----WW-WW-----------------------",
            "------WW------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------------------",
            "--------------------WW----------",
            "------------------WWWWW---------",
            "-----------------WW---WW--------",
            "----------------WW-----Ww-------",
            "---------------WW-------WW------",
            "--------------WW---------WW-----",
            "--------------WW----------WW----",
            "---------------WW----------WW---",
            "----------------WW--------WW----",
            "-----------------WW------Ww-----",
            "-------------------WW---Ww------",
            "--------------------WW-WW-------",
            "---------------------WWw--------"
            });

        // G: color = new UnityEngine.Color(0.36f, 0.36f, 0.36f, 1f);
        // -: color = new UnityEngine.Color(0.047f, 0.047f, 0.047f, 1f);
        public static readonly WaveFunctionCollapse.Tile Door = new(new string[] {
            "GGGGGGG----------GGGGGGG--------",
            "GGGGGGG----------GGGGGGG--------",
            "GGGGGGG----------GGGGGGG--------",
            "-----GGGGGGG----------GGGGGGG---",
            "-----GGGGGGG----------GGGGGGG---",
            "-----GGGGGGG----------GGGGGGG---",
            "---------GGGGGGG-----------GGGGG",
            "---------GGGGGGG-----------GGGGG",
            "---------GGGGGGG-----------GGGGG",
            "--------------GGGGGG------------",
            "GGGGGGG-------GGGGGG------------",
            "GGGGGGG-------GGGGGG------------",
            "GGGGGGG-----------GGGGGGG-------",
            "-----GGGGGGG------GGGGGGG-------",
            "-----GGGGGGG------GGGGGGG-------",
            "-----GGGGGGG-----------GGGGGGGGG",
            "----------GGGGGGG------GGGGGGGGG",
            "----------GGGGGGG------GGGGGGGGG",
            "----------GGGGGGG---------------",
            "---------------GGGGGGG----------",
            "GGGGGGG--------GGGGGGG----------",
            "GGGGGGG--------GGGGGGG----------",
            "GGGGGGG-------------GGGGGGG-----",
            "-----GGGGGGG--------GGGGGGG-----",
            "-----GGGGGGG--------GGGGGGG-----",
            "-----GGGGGGG-------------GGGGGGG",
            "----------GGGGGGG--------GGGGGGG",
            "----------GGGGGGG--------GGGGGGG",
            "----------GGGGGGG---------------",
            "GGGGGGG--------GGGGGGG----------",
            "GGGGGGG--------GGGGGGG----------",
            "GGGGGGG--------GGGGGGG----------"
            });

        public static readonly WaveFunctionCollapse.Tile MetalDark = new (new string[] {
            "---------------DWWWWWWWWWWWD----",
            "---------------DDDDDDDDDDDDD----",
            "--------------------------------",
            "DDDDDDDDDD----------------------",
            "WWWWWWWWWD----------------------",
            "DDDDDDDDDD-----DDDDDDDDDDDDDDD--",
            "---------------DWWWWWWWWWWWWWD--",
            "-----DDDDDDDDDDDDDDDDDDDDDDDDD--",
            "-----DWWWWWWWWD---DDDDDDDDD-----",
            "-----DDDDDDDDDD---DWWWWWWWD-----",
            "--------DDDDDDDDD-DDDDDDDDD-----",
            "--------DWWWWWWWD---------------",
            "--------DDDDDDDDD---------------",
            "------------DDDDDDDDDD----------",
            "------------DWWWWWWWWD----------",
            "------------DDDDDDDDDD----------",
            "------DDDDDDDDD-----------------",
            "------DWWWWWWWD-----------------",
            "------DDDDDDDDD-----DDDDDDDDDDDD",
            "--------------------DWWWWWWWWWWW",
            "--------------------DDDDDDDDDDDD",
            "------------------DDDDDDDDD-----",
            "-----DDDDDDDDDD---DWWWWWWWD-----",
            "-----DWWWWWWWWD---DDDDDDDDD-----",
            "-----DDDDDDDDDD-----------------",
            "------DDDDDDDDDDDD--------------",
            "------DWWWWWWWWWWD--------------",
            "------DDDDDDDDDDDD--------------",
            "----DDDDDDDD--------------------",
            "----DWWWWWWD--------------------",
            "----DDDDDDDD---DDDDDDDDDDDD-----",
            "---------------DWWWWWWWWWWD-----"
            });
    }
}
